#!/bin/bash

#generate call vcf from bcf file generated by samtools mpileum
#input: bcf file containing mpileup from bcftools mpileup
#output: bcf
#usage 02_bcftools_call.sh FILE SEXMAP

# Global variables
INPUT_FILE="$1"
OUTPUT="04_bcftools_call"
SEXMAP=$2
if [ ! -f $INPUT_FILE ]; then
	echo "no input file"
	exit	
fi 

if [ ! -d $OUTPUT ]; then
	echo "creating ouput directory"
	mkdir $OUTPUT
fi

# Load needed modules
module load bcftools/1.12


#list path to input file
#run bcftools call

echo $INPUT_FILE
file=$(basename $INPUT_FILE)

bcftools call -m\
  -a GP,GQ\
 -Oz\
 -G -\
 -o $OUTPUT/${file%.ubcf}.vcf.gz\
 --ploidy-file 00_ploidy_file/ploidy_map\
 -S $SEXMAP\
 $INPUT_FILE

##building reference index for merging
echo "building index"
bcftools index\
 -t\
 -o $OUTPUT/${file%.ubcf}.tbi\
 $OUTPUT/${file%.ubcf}.vcf.gz
